### PR TITLE
Focus active pane on notification removal only if the notification was focused

### PR DESCRIPTION
**Pull request by izuzak**
In https://github.com/atom/atom/issues/6439 a use-case was mentioned where dismissing a notification shouldn't focus the active pane -- programmatically dismissing a notification while some other panels are focused (e.g. the command palette). I think that makes sense and I think this change closes https://github.com/atom/atom/issues/6439.

Here's a rundown of the commits:

* 6a8617e adds a failing spec to demonstrate the problem pointed out in https://github.com/atom/atom/issues/6439. Running `apm test` at that commit produces this failure:

  ```
Notifications
  when notifications are added to atom.notifications
    when a dismissable notification is added
      it focuses the active pane only if the dismissed notification has focus
        Expected element '[object HTMLElement]' or its descendants to have focus.
          at [object Object].<anonymous> (/Users/izuzak/github/notifications/spec/notifications-spec.coffee:152:40)
          at _fulfilled (/Users/izuzak/github/atom/node_modules/q/q.js:794:54)
          at self.promiseDispatch.done (/Users/izuzak/github/atom/node_modules/q/q.js:823:30)
          at Promise.promise.promiseDispatch (/Users/izuzak/github/atom/node_modules/q/q.js:756:13)
          at /Users/izuzak/github/atom/node_modules/q/q.js:564:44
          at flush (/Users/izuzak/github/atom/node_modules/q/q.js:110:17)
          at process._tickCallback (node.js:357:13)


Finished in 14.885 seconds
48 tests, 125 assertions, 1 failure, 0 skipped
```

* 2b5f9f7 fixes the failing spec by checking if the notification had focus when it's dismissed. If it does have focus -- then the active pane is focused. If it doesn't have focus -- then focus isn't touched (assuming that whatever has focus is what should have focus).

* ff8eeaa moves the check + focus statement so that it's performed in every removal scenario, including notifications which were removed automatically after a timeout (non-dismissible notifications). This covers the case where a notification which is not dismissible is shown and the user clicks the notification, and after the timeout the notification is removed (and focus is now put to the active pane).

cc @benogle @kevinsawicki for :eyes:

### CODE REVIEW

**Comment by izuzak** [comment]
@benogle Just wondering if you have some :hourglass: to take a look at this one and see if it makes sense?

**Comment by benogle** [comment]
Sorry for the delay. This looks good :+1:

**Comment by izuzak** [comment]
I merged master into this just to make sure test are still passing, and they are. Going to :boat: this and watch for reports in case this change causes problems for anyone.

**Comment by basarat** [comment]
:rose:

**Comment by vrinek** [comment]
:metal: awesome!

**Pull request merged**
