### PR TITLE
Avoid retaining DOM elements in CommandLogger

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
TextEditorElements should not be retained in the command log because they may use a very large amount of memory.

@nathansobo This was the "memory leak" we were seeing. It would only ever retain up to 16 elements, so it wasn't too big a deal. Still, it's good to avoid this, especially with large files.

### CODE REVIEW

**Comment by benogle** [comment]
Nice. Sorry about this

**Comment by maxbrunsfeld** [comment]
No problem! I think it was a totally reasonable thing to do; just :racehorse:ing.

**Comment by kevinsawicki** [comment]
:horse_racing: :dash: nice find :mag_right:

**Comment by lee-dohm** [comment]
:metal: Nice catch!

**Comment by nathansobo** [comment]
🚱 Thanks for looking into this.

**Pull request merged**
