### PR TITLE
Removed "bottom: 0" from styling

### PR DESCRIPTION
**Pull request by gmaggio**
Removed "bottom: 0" because it was causing layout issue

### CODE REVIEW

**Comment by thomasjo** [comment]
You're going to have to justify this with some more details; please provide some screenshots demonstrating the original layout issue, and how your proposed change fixes the issue.

**Comment by gmaggio** [comment]
I'm not sure if it's due to extension conflicts but here is how the notification appears on my computer:

atom_notification_layout_problem

**Comment by Ben3eeE** [comment]
Someone had the exact same problem on discuss which did not reproduce in safe mode https://discuss.atom.io/t/strange-notification-css/36569

**Comment by thomasjo** [comment]
You can easily verify whether it's caused by a community package by starting Atom in safe mode;
`atom --safe`. But I can already tell you this is caused by a community package, but not which one. Figuring that out, is something you'll have to figure out, for example by disabling packages until the problem goes away.

Since this is not addressing a core UI bug, and is caused by a bug in some unknown community package, I'm going to close this for the time being. If it turns out that the underlying bug cannot be solved in the culprit community package, then feel free to re-open this PR for further consideration.

**Pull request closed without merging**
