### PR TITLE
Don't assume filePath is non-empty

### LINKED ISSUE #107: Uncaught TypeError: Cannot read property '0' of null
Press the run button in the toolbar of the package "love-ide"

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.62.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-issue.js:222

TypeError: Cannot read property '0' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-issue.js:222:64
    at NotificationIssue.module.exports.NotificationIssue.getPackageName (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-issue.js:241:54)
    at NotificationIssue.module.exports.NotificationIssue.getRepoUrl (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-issue.js:163:26)
    at atom-notification.NotificationElement.renderFatalError (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:167:28)
    at atom-notification.NotificationElement.render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:159:21)
    at atom-notification.NotificationElement.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:50:33)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:96:42)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:83:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:68:21)
    at Object.Notifications.addNotificationView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:130:60)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/main.js:34:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at NotificationManager.module.exports.NotificationManager.addNotification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:54:20)
    at NotificationManager.module.exports.NotificationManager.addFatalError (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:45:19)
    at /Users/felixkranich/.atom/packages/love-ide/lib/main.js:51:25
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:25 core:move-right (atom-text-editor.editor.is-focused)
     -1:24.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:24.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:23.4.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:22.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:11.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:05.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:00.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:59.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.1.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:57.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:57.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:30.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:28.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jscs",
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "autocomplete-java"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "emmet"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-ternjs, v0.12.2
autocomplete-glsl, v0.2.3
autocomplete-love, v0.2.0
close-other-tabs, v0.1.0
color-picker, v2.0.14
documentation-renderer, v0.2.1
emmet, v2.3.17
file-types, v0.5.1
hyperclick, v0.0.35
hyperclick-love, v0.2.0
java-importer, v1.4.1
language-arduino, v0.4.1
language-csharp, v0.11.0
language-glsl, v2.0.1
language-htaccess, v0.1.1
language-lua, v0.9.4
language-ruby, v0.67.0
language-rust, v0.4.5
language-unity-shaderlab, v1.0.1
language-x86, v0.1.0
linter, v1.11.3
linter-alex, v1.7.0
linter-clang, v3.3.0
linter-gcc, v0.5.11
linter-javac, v1.4.0
linter-jshint, v1.2.2
linter-luaparse, v0.2.0
linter-ruby, v1.2.1
linter-rust, v0.3.0
linter-tslint, v0.6.0
love-ide, v0.7.0
minimap, v4.19.0
pigments, v0.19.5
remote-sync, v3.5.0
save-autorun, v0.3.3
tool-bar, v0.1.10
tool-bar-main, v0.0.8
travis-ci-status, v0.18.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by 50Wliu**
Looks like we don't even have the luxury of that.

Fixes #107.

Any tips on how to write specs for this?  I'm not sure how to make the file path empty.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Test added, woo!

**Comment by 50Wliu** [comment]
I've removed the test as it was useless.  `options.detail` will always have at least a value of `:` when processing an uncaught exception ([source](https://github.com/atom/notifications/blob/f6dd2b75ea1729109334779c897798d3714a07d7/lib/main.coffee#L40)), so it's impossible for filePath to have a length of 0.  love-ide was probably doing something else wrong that led to this exception along the way.

**Comment by mnquintana** [comment]
@50Wliu Do you think this is still needed or should we close this out?

**Comment by 50Wliu** [comment]
I'm still not convinced this is something that can happen without other things going incredibly wrong.

**Pull request closed without merging**
